dashboard/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index')
]

friend/urls.py
from django.conf.urls import url
from .views import index, add_friend

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_friend', add_friend, name='add_friend'),
 ]

linked_out/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import user_profile.urls as user_profile
import dashboard.urls as dashboard
import status.urls as status
import friend.urls as friend
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(
        url='/status/', permanent=True),
        name='index'),
    url(r'^user_profile/', include(user_profile, namespace="user_profile")),
    url(r'^dashboard/', include(dashboard, namespace="dashboard")),
    url(r'^status/', include(status, namespace="status")),
    url(r'^friend/', include(friend, namespace="friend")),
]

status/urls.py
from django.conf.urls import url
from .views import index, add_status, delete_status

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', add_status, name='add_status'),
    url(r'^delete/(?P<pk>\d+)/$', delete_status, name='delete_status')
]

user_profile/urls.py
from django.conf.urls import url
from .views import index


#url for app, add your URL Configuration

urlpatterns = [
#TODO Implement this
	url(r'^$', index, name='index'),

]

dashboard/models.py
from django.db import models

# Create your models here.

friend/models.py
from django.db import models

# Create your models here.
class Friend(models.Model):
	name = models.CharField(max_length=27)
	url = models.URLField()
	created_date = models.DateTimeField(auto_now_add=True)

status/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    status = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

user_profile/models.py
from django.db import models
from datetime import date

DATE_INPUT_FORMATS = ('%d-%m-%Y')


# Create your models here.


class Person(models.Model):
    name = models.CharField(max_length=30)
    birthdate = models.DateField(default=date.today)
    gender = models.CharField(max_length=6)
    description = models.CharField(max_length=100)
    email = models.EmailField()

class Expertise(models.Model):
    expertise = models.CharField(max_length=255)

class PhotoURL(models.Model):
    model_pic = models.CharField(max_length=255)

friend/forms.py
from django import forms

class Add_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan URL',
    }
    name_attrs = {
        'type':'text',
    	'class':'form-control',
        'placeholder': 'Enter your name'
    }
    url_attrs = {
        'type':'url',
    	'class':'form-control',
        'placeholder': 'Enter your website (with http://)'
    }

    name = forms.CharField(label='Name', required=True, widget=forms.TextInput(attrs=name_attrs))
    url = forms.URLField(label='URL', required=True, widget=forms.TextInput(attrs=url_attrs))

status/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    status_attrs = {
        'type': 'text',
        'cols': 150,
        'rows': 4,
        'class': 'status-form-textarea',
        'placeholder': "What's happening?"
    }

    status = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=status_attrs))

dashboard/views.py
from django.shortcuts import render
from status.models import Status
from friend.models import Friend
from user_profile.models import Person, PhotoURL
# TODO import status.models
# TODO import fiends.models
# TODO import user_profile.models

response = {}


def index(request):
    html = "dashboard/dashboard.html"

    personName = Person.objects.all()[0].name
    personPic = PhotoURL.objects.all()[0].model_pic
    statusCount = Status.objects.all().count()
    statusMsg = statusMsg = "Post" if statusCount <= 1 else "Posts"
    friendCount = Friend.objects.all().count()
    friendMsg = "Person" if friendCount <= 1 else "People"
    if (statusCount > 0):
        lastStatus = Status.objects.all()[statusCount - 1]
        lastDesc = lastStatus.status
        lastDate = lastStatus.created_date
    else:
        lastDesc = "Tidak ada Status"
        lastDate = None

    response["author"] = "Rayza"
    response["personName"] = personName
    response["personPic"] = personPic
    response["statusCount"] = statusCount
    response["statusMsg"] = statusMsg
    response["friendCount"] = friendCount
    response["friendMsg"] = friendMsg
    response["lastDesc"] = lastDesc
    response["lastDate"] = lastDate

    return render(request, html, response)

friend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Add_Form
from .models import Friend
from urllib.request import urlopen
from urllib.error import URLError

# Create your views here.
response = {}

def index(request):
	friend = Friend.objects.all()
	response['friend'] = friend
	html = 'add_friend.html'
	response['add_form'] = Add_Form
	response["author"] = "Azmie"
	return render(request, html, response)

def add_friend(request):
	form = Add_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['name'] = request.POST['name']
		response['url'] = request.POST['url']
		friend = Friend(name=response['name'], url=response['url'])
		friend.save()
		return HttpResponseRedirect('/friend/')
	else:
		return HttpResponseRedirect('/friend/')

def url_is_valid(url):
    try:
        thepage = urlopen(url)
    except URLError as e:
        return False
    else:
        return True

status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Status_Form
from .models import Status

description='tMaster of contrapuntal composition and professional harpsichord player'
name='Johann Sebastian Bach'
gender='Male'
email='jsbach@gmail.com'
author='Hadlina Rahmadinni'


# Create your views here.
response = {}

def index(request):
    response['author'] = author #TODO Implement yourname
    status = Status.objects.all().order_by('-created_date')
    response['database'] = status
    html = 'update_status/update_status.html'
    response['status_form'] = Status_Form
    response['profile_name'] = name
    return render(request, html, response)

def add_status(request):
    form = Status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['status'] = request.POST['status']
        status = Status(status=response['status'])
        status.save()
        return HttpResponseRedirect('/status/')
    else:
        return HttpResponseRedirect('/status/')

def delete_status(request, pk):
    status = Status.objects.filter(pk=pk).first()
    if status != None:
        status.delete()
        pass
    return HttpResponseRedirect('/status/')

user_profile/views.py
from django.shortcuts import render
from .models import Person, Expertise, PhotoURL

# Create your views here.



def index(request):
    html = 'user_profile.html'

    person = Person.objects.create(name="Johann Sebastian Bach", birthdate="1685-03-31", gender="Male", description="Master of contrapuntal composition and professional harpsichord player", email="jsbach@gmail.com")
    expertise = Expertise.objects.create(expertise ="Contrapuntal composition")
    expertise = Expertise.objects.create(expertise ="Church leading musician")
    expertise = Expertise.objects.create(expertise ="Glorifying God")
    model_pic = expertise = PhotoURL.objects.create(model_pic ="http://www.bachsociety.org/wp-content/uploads/2017/01/Johann-sunglasses.jpg")

    response = {} #TODO Implement yourname
    response['author']= "Kezia Irene"
    response['name'] = Person.objects.all()[0].name
    response['birthdate'] = Person.objects.all()[0].birthdate
    response['gender'] = Person.objects.all()[0].gender
    response['expertise'] = Expertise.objects.all()[0:3]
    response['description'] = Person.objects.all()[0].description
    response['email'] = Person.objects.all()[0].email
    response['model_pic'] = PhotoURL.objects.all()[0].model_pic

    return render(request, html, response)

dashboard/templates/dashboard/dashboard.html
{% extends "layout/base.html" %}
{% load static %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}" />
{% endblock %}

{% block title %}
Dashboard by {{ author }}
{% endblock %}

{% block content %}
<!-- TODO -->
<div class="page-header">
    <h1 class="text-center" style="padding-top: 10px">Dashboard</h1>
</div>

<div class="container">
    <div class="row" style="padding-bottom: 10px">
        <div class="col-sm-12">
            <div class="text-center">
                <img src="{{ personPic }}" class="img-circle" width="200" height="200">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <h2 class="text-center">{{ personName }}</h2>
        </div>
    </div>
    <hr class="blue-hr">
    <div class="row">
        <div class="col-sm-6">
            <div class="text-center">
                <div class="alert alert-info" style="margin: 20px 80px; padding: 0px">
                    <h3 style="margin: 0px">Feed</h3>
                    <p>{{ statusCount }} {{ statusMsg }}</p>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="text-center">
                <div class="alert alert-info" style="margin: 20px 80px; padding: 0px">
                    <h3 style="margin: 0px">Friends</h3>
                    <p>{{ friendCount }} {{ friendMsg }}</p>
                </div>
            </div>
        </div>
    </div>
    <hr class="blue-hr">
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            {% if not lastDate %}
                <div class="text-center alert alert-danger" style="margin: 10px 50px">
                    <h3>No Status</h3>
                </div>
            {% else %}
                <div class="col-sm-12">
                    <div class="text-center">
                        <h2>"{{ lastDesc }}"</h2>
                        <small>- {{ lastDate }} -</small>
                    </div>
                </div>
            {% endif %}
        </div>
        <div class="col-sm-3"></div>
    </div>
</div>
{% endblock %}

friend/templates/add_friend.html
{% extends "layout/base.html" %}
{% block title %}
Add Friend by {{author}}
{% endblock %}
{% block content %}
<style>
.alert-dismissable {
	width: 25%;
	font-size: 85%;
}
</style>
<div style="padding-left:55px;padding-right:55px"
<section name='add-input' id='add-input'>
	<h1 class="main-title">Add Friend</h1>
	<form id='form' method="POST" action="{% url 'friend:add_friend' %}">
		{% csrf_token %}
        {{ add_form }}
        <br>
	    <button id="submit" type="submit" class="btn pull-right btn-primary" style="border-radius:50px">Add Friend</button>
	</form>
	{% if not valid and not first %}
	<div class="alert alert-danger alert-dismissable">
		<a href="#" class="close" data-dismiss="alert" aria-label="close" >&times;</a>
		<strong>Sorry!</strong> You've added an invalid friend.
	</div>
{% endif %}
</section>
<section name='friend-list' id='friend-list'>
	<h4>List Friend</h4>
	<table class='table table-responsive table-hover'>
		<tbody>
			{% if friend %}
				{% for i in friend %}
				<tr>
					<td><img src="https://usercontent2.hubstatic.com/5209067_f520.jpg"
						style="width:40px;height:40px;border-radius:40px"></td>
					<td> {{ i.name }} </td>
					<td></td>
					<td> <a href="{{ i.url }}">{{ i.url }}</a> </td>
					<td> Added 	{{ i.created_date }} </td>
				</tr>
				{% endfor %}
			{% else %}
			<div class="alert alert-danger text-center">
                <strong>Oops!</strong> You don't have any friend :(
            </div>
            {% endif %}
		</tbody>
	</table>
</section>
</div>
{% endblock %}

linked_out/templates/status.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<style>
    table, th, td {
        border: 2px solid black;
        background-color: #f2eada;
        text-align: left;
        padding: 5px;
    }
    .subject{
        font-size: 20px;
        font-family: "Gill Sans";
        color: black;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: grey;
    }
</style>
<body style="background-color: pink">
    <div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Hadlina's</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/lab-2/">Home</a>
              </li>
              <li class="nav-item" >
                <a class="nav-link" href="/lab-2-addon/">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/lab-3/">Diary</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/lab-4/">More!!</a>
              </li>
            </ul>
          </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}
</html>

status/templates/update_status/update_status.html
{% extends "layout/base.html" %}

{% block content %}
<title>
    {% block title %} Status By {{author}}{% endblock %}
</title>
<div class="container">
    <section name="input-list" id="input-list">
        <form style="font-size: 20px;" id="form" method="POST" action="{% url 'status:add_status' %}">
            <h2>Update Status</h2>
            {% csrf_token %}
            {{ status_form }}
            <input id="submit" type="submit" class="btn btn-lg btn-block" value="Post" style="width: 75px; background-color: lightblue; border-radius: 55px">
            <br>
        </form>
    </section>
    <section name="my-list" id="my-list">
        <h2 class="title">Your Status</h2>
        <div class="flex">
            {% if database %}
                {% for data in database %}
                    <div class="flex-item">
                        <div class="status-list">
                            <div class="status-profile">
                                <div>
                                    <a href="{% url 'user_profile:index' %}">
                                    <p style="font-size: 25px; color: black"><img src="http://www.bachsociety.org/wp-content/uploads/2017/01/Johann-sunglasses.jpg" style="border-radius: 15%; width: 80px; height: 75px; margin: 10px;">{{profile_name}}</p>
                                </a>
                                </div>
                            </div>
                            <div class="description" style="font-size: 20px;">
                                {{data.status}}
                            </div>
                            <div class="status-date-added">
                                {{data.created_date}}
                                <br><br>
                            </div>
                            <div class="to-do-list-description">
                                {{data.description}}
                            </div>
                            <div class="to-do-list-delete">
                                <div class="to-do-list-delete-button" data-id="{{data.id}}" style="width: 60px; background-color: red; font-size: 20px; position: center; border-radius: 5px;">Delete</div>
                            </div>
                        </div>       
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> There isn't status yet.
            </div>
            {% endif %}
        </div>
    </section>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script type="application/javascript">
    $(function() {
        $('.to-do-list-delete-button').click(function() {
            var id = $(this).data('id')
            location.href = "/status/delete/" + id + "/"
        });
    });
</script>
</div>

{% endblock %}  

templates/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Tugas 1 PPW - LinkedOut">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% block style %}
    <!-- styles goes here -->
    {% endblock %}
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body style="background-color: #dfe2e1">

    <header>
        {% include "partials/header.html" %}
    </header>
    <div style="margin-top: 55px" >
        {% block content %}
            <!-- content goes here -->
        {% endblock %}
    </div>
    <hr>
    <footer>
        {% block footer %}
        {% include "partials/footer.html" %}
        {% endblock %}
    </footer>

</body>
</html>

templates/partials/footer.html
<p align="center">Made with Love by {{author}}</p>

templates/partials/header.html
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="http://linked-out.herokuapp.com/">Linked-Out</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/user_profile/">Profile</a></li>
        <li><a href="/status/">Status</a></li>
        <li><a href="/friend/">Add Friend</a></li>
        <li><a href="/dashboard/">Dashboard</a></li>
      </ul>
    </div>
  </div>
</nav>

user_profile/templates/user_profile.html
{% extends "layout/base.html" %}
{% load staticfiles %}

{% block style %}

    <!-- bootstrap csss -->
    <link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/user_profile.css' %}" />
{% endblock %}
{% block title %}
User Profile by Kezia Irene
{% endblock %}
{% block content %}
<div class="profile">
<h1>Profile</h1>
</div>
<hr/>

<section name="name">
    <p align = "center">
         <img src={{model_pic}} class="img-circle" widht="200" height="200">
    </p>

    <p align = "center">
        <div class = "name">
        <h2 align="center">{{name}}</h2>
        </div>
    </p>
</section>
<hr/>
<section name="about_me">
    <table class="table" align="center">
        <tr>
            <td>Birthday</td>
            <td>{{birthdate}}</td>
        </tr>
        <tr>
            <td>Gender</td>
            <td>{{gender}}</td>
        </tr>
        <tr>
            <td>Expertise</td>
            <td>
                {% for data in expertise %}
                    <span class="badge badge-pill badge-primary" id="bege">{{data.expertise}}</span>
                {% endfor %}
            </td>
        </tr>
        <tr>
            <td>Description</td>
            <td>{{description}}</td>
        </tr>
    </table>
</section>


{% endblock %}